### ISSUE TITLE
~2х overhead on operation

### ISSUE THREAD

**Issue by AntonKozlov** [true-real-michael/sha256-musl-riscv-optimization#3]
https://github.com/true-real-michael/sha256-musl-riscv-optimization/blob/1b49fd9097b53f1a6cf031276e753a84483e4e9f/modified_sha/crypt_sha256_musl_original.c#L318

Apparently, for each sha256 request an another one is performed with test data

**Comment by misha-kis** [comment]
It is true, however, it is also the case for the original implementation. And, for sake of security, I am not sure whether it should be removed.
